@extends('layouts.app')

@push('css')
    <style>
    </style>
@endpush
@section('content')


<div id="kt_app_content_container" class="app-container d-flex justify-content-center align-items-center">
	<div class="card mb-5 mb-xl-10 bg-content-card card-no-border bg-transparent w-100">
		<div id="kt_account_settings_profile_details">
			<div class="card-body p-9 card p-5 bg-section card-no-border">

				<div class="row">
					<div class="col-md-12 col-sm-12">
                        <h1 class="text-dark fw-bold fs-2x">
                            Generated Report List
                        </h1>
					</div>
				</div>

                <div class="row flex-row mt-10">
                    <div class="col-md-12">
                        <div class="responsive-table">
                            <table class="dcms-table" id="general-tab">
                                <thead class="table-head text-light">
                                    <tr>
                                        <th>No.</th>
                                        <th>Date Generate</th>
                                        <th>Report No.</th>
                                        <th>Report Type</th>
                                        <th>Status Process</th>
                                        <th>Generated By</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                            </table>

                        </div>

                    </div>

                </div>
				
			</div>
		</div>
	</div>
</div>

@endsection
@push('script')
    <script>
        (function ($) {

            var table = $('#general-tab').DataTable({
                dom: 'lfrtip',
                @include('layouts._partials.lengthMenu')
                processing: true,
                serverSide: false,
                ajax:  {
                    "url" :"{{ route('report.general.reportGeneralDatatable') }}",
                    "method": 'POST',
                },
                columns: [
                    { name: 'indexNo', data: 'indexNo', class: 'text-center' },
                    { name: 'GRCD', data: 'GRCD', class: '' },
                    { name: 'GRNo', data: 'GRNo', class: '' },
                    { name: 'GR_GRTCode', data: 'GR_GRTCode', class: 'text-center' },
                    { name: 'GRStatus', data: 'GRStatus', class: 'text-center' },
                    { name: 'GRCB', data: 'GRCB', class: 'text-center' },
                    { name: 'action', data: 'action', class: 'text-center' },

                ],
                fnDrawCallback: function(oSettings) {
                    var api = this.api();
                    api.column(0, { page: 'current' }).nodes().each(function(cell, i) {
                        cell.innerHTML = i + 1;
                    });
                }
            });
            table.buttons().container().appendTo('.button-table-export');

        })(jQuery);

    </script>
@endpush
