<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document Signs Report</title>
    <link href="{{ public_path('assets/css/custom/report.css') }}" rel="stylesheet" type="text/css" />
</head>
<body style="background:white !important;">

    <div class="row">       
        <div class="column-6 text-right">
            <img class="w-50" src="{{ public_path('assets/images/icon/logo-dcms-blue.png') }}">
            <div class="text-right fs-12 text-bold">
                Digital Certificate Management System
            </div>
        </div>
        <div class="column-4">
            <div class="text-right fs-9">
                Generated By: {{ $generatedBy }}  
            </div>

            <div class="text-right fs-9">
                Generated Date: {{ $dateNow }}  
            </div>

            <div class="text-right fs-9">
                Generated Time: {{ $timeNow }}  
            </div>
        </div>
    </div>

    <br>

    <div class="text-center">
        <b>Document Signs Report</b>
    </div>
    
    <br>

    <div class="page_break fs-9">
        <table class="w-100">
            <tr class="nowrap bg-transparent">
                <th>No.</th>
                <th>Document Sign No.</th>
                <th>Document Signed Date</th>
                <th>Certificate No.</th>
                <th>ID/Register No.</th>
            </tr>
            @foreach($data as $index => $sign)

            <tr class="text-center">
                <td>{{ $loop->iteration }}</td>
                <td>{{ $sign->SDNo }}</td>
                <td>{{ \Carbon\Carbon::parse($sign->SDCD)->format('d/m/Y') }}</td>
                <td>{{ $sign->CENo }}</td>
                <td>{{ $sign->CEIDNo }}</td>
            </tr>


            @endforeach
            
        </table>
    </div>

</body>
</html>
